if: tag IS blank #only build commits
language: generic
env:
  global:
    - secure: "jAuN252Zy/dPhaiswx6GIDpWzKl72jRnLk7tH8qYsxXVx64rZrkHdFMZ606QDyEhWTmO1MMAXg62draFSN4kkg5oSOV6tkt4/11hm7loS6HfchMItdLpVdrX3nq21thgo1TdkRt7MI5Ke0i+xr/8M3+FVaJKp6u9OK07vVavRBcHH8q3dn1CscgRtTc2EuKWHEgwez9mGoFwF2ppjAWfVH3E/1Vev7I4Kn0oGVxRQ86GnTTJp3R9h8n/O2S/j63P6sCD+DqICquPe5JQBe9O9AOu660sJmnmv5YT/yoChJ/0/lOGm9nehK5h+jQxQiTx7a9N4KYJEHEPf7dVI4Lvut/pbYjaxoM6hYpJl5GWRZf9RSg0XLzkjKWA0se44EW1x0hlLXmYBqFIaufTHb1SXW+eTs4H1gZvmGKL6nausi+cJEn3G9iSpmF0A6nv6zzUK2pgDPd1CcKaVSvqN8kZmzM5/GQKztIOSBYZ0Vc8G0RzDsFcrorPu3+CB+IiWdFlHalnUHjXTP++DMIMMzun8jKfTqUnn2I1I3xqGRBt5O9LCG9/CVg2VEMKPGigXGPFtpMIT7NsQvc6Yv0TthRVmrId92b21EZ4UhHyk5/J4bg1jNO7XKmTdwvlCKaIJFJ6zGfY/n1qdCM7YLyGFefCI+Fpc1aHoi/fuDUNH8oHw6Y=" #$GITHUB_TOKEN (travis)
install:
  true
script:
  # - ./travis-install-webrtc-dep.sh
  #Depot tools
  - cd $HOME
  - mkdir webrtc-dep
  - cd webrtc-dep
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=$PATH:$HOME/webrtc-dep/depot_tools #this seems to only work outside of scripts
  #switch back to work directory
  - cd $TRAVIS_BUILD_DIR
  #gclient stuff
  - mv .gclient ../.gclient #move gclient to parent directory to use as config
  - sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" DEPS # not get resources when gclient sync
  - mv `pwd` ../src #rename the current directory (repo root) to src so all the scripts work without problem
  - gclient sync
  - chmod u+x tools_webrtc/android/build_aar.py
  - ./tools_webrtc/android/build_aar.py
  - chmod u+x publish-maven.sh
  - ./publish-maven.sh #publish to maven repo
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jack Zhang"
  - git config --local user.email "zhangmengyu10@gmail.com"
  - export BUILD_NUM=$(./get-build-num.sh)
  - git tag -a "AutoBuild-$BUILD_NUM" -m "Automatic Build $BUILD_NUM - $(date +'%Y-%m-%d %H:%M:%S.%3N') - $(git log --format=%h -1)"
deploy:
  provider: releases
  on:
    branch: knock-branch
  api_key:
    secure: "NDxiqck5a7X+Xq0QdOjOXT90HvRNXZxQRGcuufya+EwOGLcht/8SP+WFsPbu6P++icLBdQSZhmGSmaywaV6EWBNxoOtDrTlbLuD+YMl8CKbOOykx6hd8W2QAowYuudP9fZfWJsO7S3aiAWnBKak8et6uyjcTUjj82nP47bzG7p3BPYPrgx5BDL7XPeXzbWyp33dmWRio/zw9qJn2kKwB1lZBTyuRODCdrKiWTpA+H7QqvBhQcDQzMgf6Ooy5S4wEvl2nQZAORJ1LTHNB4e/FL4e0jon6covN0Q1aXOarphWkeDh3vVYDpMG9cyRCScYvL7GZ1yWyfwzWBdBKr1zYHDkCPMTUmgKQfl0pTL8t/M5nsz6TYSbjIbXyJyMo8fM0RI9Rjmq+jjiX+adFj85m+Za/N3OejauH5qrAMbpQTq+e0e6RD5i2DiQ0fRqEjaFQ9cmaGZcwGCG+H2LWQFYN25KHzkt4QqaE8D8RhrtGmfhXTvZz4CnIvpO+w+OVJwX5k/G8APKy3bMbtlQrovnvqRDaDlzMZM/z7/wTqknmi7Oj+TbsYBIwG2Wc4pzGKYyRPM0tTMqGO0hUCA398VRwPWnd9xLKGPUpWBkb1oB8JTGkzFuKtmCxBZceuFwekXmntX9j4cMbxxVCV0sYeV1bJdujbFdma3fWuyuly2K1NSc="
  file: libwebrtc.aar    
  skip_cleanup: true

