language: minimal
install:
  - chmod +x travis-install-webrtc-dep.sh
script:
  - ./travis-install-webrtc-dep.sh
  - export PATH=$PATH:$HOME/webrtc-dep/depot_tools #this seems to only work outside of scripts
  - gclient sync
  - chmod u+x tools_webrtc/android/build_aar.py
  - ./tools_webrtc/android/build_aar.py
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jack Zhang"
  - git config --local user.email "zhangmengyu10@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  on:
    branch: knock-branch
  api_key:
    secure: "NDxiqck5a7X+Xq0QdOjOXT90HvRNXZxQRGcuufya+EwOGLcht/8SP+WFsPbu6P++icLBdQSZhmGSmaywaV6EWBNxoOtDrTlbLuD+YMl8CKbOOykx6hd8W2QAowYuudP9fZfWJsO7S3aiAWnBKak8et6uyjcTUjj82nP47bzG7p3BPYPrgx5BDL7XPeXzbWyp33dmWRio/zw9qJn2kKwB1lZBTyuRODCdrKiWTpA+H7QqvBhQcDQzMgf6Ooy5S4wEvl2nQZAORJ1LTHNB4e/FL4e0jon6covN0Q1aXOarphWkeDh3vVYDpMG9cyRCScYvL7GZ1yWyfwzWBdBKr1zYHDkCPMTUmgKQfl0pTL8t/M5nsz6TYSbjIbXyJyMo8fM0RI9Rjmq+jjiX+adFj85m+Za/N3OejauH5qrAMbpQTq+e0e6RD5i2DiQ0fRqEjaFQ9cmaGZcwGCG+H2LWQFYN25KHzkt4QqaE8D8RhrtGmfhXTvZz4CnIvpO+w+OVJwX5k/G8APKy3bMbtlQrovnvqRDaDlzMZM/z7/wTqknmi7Oj+TbsYBIwG2Wc4pzGKYyRPM0tTMqGO0hUCA398VRwPWnd9xLKGPUpWBkb1oB8JTGkzFuKtmCxBZceuFwekXmntX9j4cMbxxVCV0sYeV1bJdujbFdma3fWuyuly2K1NSc="
  file: libwebrtc.aar    
  skip_cleanup: true

