language: minimal
install:
  ./travis-install-webrtc-dep.sh
script:
  tools_webrtc/android/build_arr.py
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jack Zhang"
  - git config --local user.email "zhangmengyu10@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  on:
    branch: knock-branch
  api_key:
    ///
  file: libwebrtc.aar    
  skip_cleanup: true

